# Generated by Django 4.0 on 2023-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesmodel',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
