# Generated by Django 4.0 on 2023-04-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('API', '0004_alter_issuesmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesmodel',
            name='assignee_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to='authentication.usermodel'),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='author_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_user_id', to='authentication.usermodel'),
        ),
    ]
