# Generated by Django 4.0 on 2023-04-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('API', '0005_alter_issuesmodel_assignee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='comment_id',
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='assignee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to='authentication.usermodel'),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='author_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user_id', to='authentication.usermodel'),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='priority',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='issuesmodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
